version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      DEBUG: ${DEBUG:-0}
      AWS_DEFAULT_REGION: eu-west-2
      SERVICES: sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_bootstrap:/etc/localstack/init/ready.d/"

  request-api:
    build:
      context: .
      dockerfile: request-api/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      SQS_QUEUE_NAME: request-queue
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
    restart: on-failure
    ports:
      - "8000:8000"

  request-db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: request_database
    restart: on-failure

  request-processor:
    build:
      context: .
      dockerfile: request-processor/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      SQS_QUEUE_NAME: request-queue
      SQS_RECEIVE_WAIT_SECONDS: 10
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
      NOTIFY_BASE_URL: http://govuk-notify-stub:8080 # https://api.notifications.service.gov.uk
      NOTIFY_API_KEY: key_name-c745a8d8-b48a-4b0d-96e5-dbea0165ebd1-8b3aa916-ec82-434e-b0c5-d5d9b371d6a3
      NOTIFY_TEMPLATE_ID: f33517ff-2a88-4f6e-b855-c550268ce08a
    restart: on-failure
    deploy:
      replicas: 2

  govuk-notify-stub:
    image: wiremock/wiremock:3.3.1
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--verbose"]
    volumes:
      - "./govuk-notify-stub/wiremock:/home/wiremock"
    ports:
      - "8001:8080"