version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      DEBUG: ${DEBUG:-0}
      AWS_DEFAULT_REGION: eu-west-2
      SERVICES: sqs, s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_bootstrap:/etc/localstack/init/ready.d/"

  request-api:
    build:
      context: .
      dockerfile: request-api/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      CELERY_BROKER_URL: sqs://ABCDEFGHIJKLMNOPQRST:ZYXK7NiynGlTogH8Nj+P9nlE73sq3@localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      SQS_QUEUE_NAME: request-queue
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
      USE_CELERY: true
    restart: on-failure
    ports:
      - "8000:8000"

  request-db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: request_database
    restart: on-failure

  request-processor-celery:
    build:
      context: .
      dockerfile: request-processor-celery/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      # CELERY_BROKER_URL: sqs://@sqs.eu-west-2.amazonaws.com
      CELERY_BROKER_REGION: eu-west-2
      CELERY_BROKER_IS_SECURE: "true"
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
      REQUEST_FILES_BUCKET_NAME: dluhc-data-platform-request-files-local
    restart: on-failure
    deploy:
      replicas: 1
    volumes:
      - "./request-processor-celery/docker_volume:/opt"
