name: Test
run-name: Test - ${{ github.head_ref || github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  test-request-api:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install test dependencies with pip
        working-directory: ./request-api
        run: |
          pip3 install -r requirements/test_requirements.txt

      - name: Run Lint and Tests
        working-directory: ./request-api
        run: make test

  test-request-processor:
    runs-on: ubuntu-22.04
    steps:
      - name: Install GDAL binary package
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install gdal-bin
          gdalinfo --version

      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install test dependencies with pip
        working-directory: ./request-processor
        run: |
          pip3 install -r requirements/test_requirements.txt

      - name: Download specification files
        working-directory: ./request-processor
        run: make specification

      - name: Lint, Test, Coverage
        working-directory: ./request-processor
        run: make all